server:
  port: 8060
  undertow:
    #是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
spring:
  profiles:
    active: '@profileActive@'
  application:
    name:  '@pom.artifactId@'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: root
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  security:
    user:
      name: "admin"
      password: "admin"
  redis:
    database: 0
    host: 183.245.38.243
    port: 56379
    password: redis@123456

logging:
  level:
    root: INFO
    org.apache.ibatis: info
    java-utils: debug
  config: classpath:logback.xml

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

token:
  secretKey: 9ac93552c203dde2a133a0988faa05b9
  ttl: 7


# 读取这里的白名单在网关过滤掉url
url:
  white-list:
    - /user/login
    - /admin/login
    - /doc.html
    - bycdao-ui
    - swagger-resources

alipay:
  app_cert_path: /crt/appCertPublicKey_2021001157613961.crt
  alipay_root_cert_path: /crt/alipayRootCert.crt
  alipay_cert_path: /crt/alipayCertPublicKey_RSA2.crt

upload-file:
  imgPath: /images/admin-organization
  imgUrl: http://vip.amsure.cn:8050/images/admin-organization/
  imgThumbPath: /images/admin-organization
  imgThumbUrl: http://vip.amsure.cn:8050/thumb/


swagger:
  base_package: com.ddcx.app.provider.uac.web
  enable: true
  title: Utils
  server_url: http://localhost/utils/uac/
  version: 1.0
  description: Utils
